apiVersion: v1
kind: Service
metadata:
  name: aggregated-nosql-repository
spec:
  selector:
    app: aggregated-nosql-repository
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregated-nosql-repository
spec:
  selector:
    matchLabels:
      app: aggregated-nosql-repository
  template:
    metadata:
      labels:
        app: aggregated-nosql-repository
        function: urban
    spec:
      containers:
      - name: aggregated-nosql-repository
        image: sersomon/aggregated_nosql_repository:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
        ports:
        - containerPort: 8080
