apiVersion: v1
kind: Service
metadata:
  name: mobility-api
spec:
  selector:
    app: mobility-api
  ports:
  - port: 8080
    targetPort: 8080


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobility-api
spec:
  selector:
    matchLabels:
      app: mobility-api
  template:
    metadata:
      labels:
        app: mobility-api
        function: urban
    spec:
      containers:
      - name: mobility-api
        image: sersomon/mobility_api:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
        ports:
        - containerPort: 8080
