apiVersion: v1
kind: Service
metadata:
  name: municipal-api
  namespace: urban
spec:
  selector:
    app: municipal-api
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: municipal-api
  namespace: urban
spec:
  selector:
    matchLabels:
      app: municipal-api
  template:
    metadata:
      labels:
        app: municipal-api
        function: urban
    spec:
      containers:
      - name: municipal-api
        image: sersomon/municipal_api:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: APP.JWT.KEY
            valueFrom:
              secretKeyRef:
                name: municipal-api-secret
                key: admin-token
          - name: MOBILITY-API
            valueFrom:
              configMapKeyRef:
                name: apis-url-configmap
                key: mobility-api
          - name: POLLUTION-API
            valueFrom:
              configMapKeyRef:
                name: apis-url-configmap
                key: pollution-api
          - name: AUTH-API
            valueFrom:
              configMapKeyRef:
                name: apis-url-configmap
                key: auth-api
          - name: AGGREGATED-NOSQL-REPOSITORY
            valueFrom:
              configMapKeyRef:
                name: apis-url-configmap
                key: aggregated-nosql-repository
        ports:
        - containerPort: 8080
