apiVersion: v1
kind: Service
metadata:
  name: pollution-sql-repository
spec:
  selector:
    app: pollution-sql-repository
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollution-sql-repository
  namespace: urban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pollution-sql-repository
  template:
    metadata:
      labels:
        app: pollution-sql-repository
        function: urban
    spec:
      containers:
        - name: pollution-sql-repository
          image: sersomon/pollution_sql_repository:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
          - containerPort: 8080