apiVersion: v1
kind: Service
metadata:
  name: pollution-api
  namespace: urban
spec:
  selector:
    app: pollution-api
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollution-api
  namespace: urban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pollution-api
  template:
    metadata:
      labels:
        app: pollution-api
        function: urban
    spec:
      containers:
        - name: pollution-api
          image: sersomon/pollution_api:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: POLLUTION-SQL-REPOSITORY
              valueFrom:
                configMapKeyRef:
                  name: apis-url-configmap
                  key: pollution-sql-repository
            - name: POLLUTION-NOSQL-REPOSITORY
              valueFrom:
                configMapKeyRef:
                  name: apis-url-configmap
                  key: pollution-nosql-repository
            - name: AUTH-API
              valueFrom:
                configMapKeyRef:
                  name: apis-url-configmap
                  key: auth-api
          ports:
          - containerPort: 8080