apiVersion: v1
kind: Service
metadata:
  name: pollution-sql-repository
  namespace: urban
spec:
  selector:
    app: pollution-sql-repository
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollution-sql-repository
  namespace: urban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pollution-sql-repository
  template:
    metadata:
      labels:
        app: pollution-sql-repository
        function: urban
    spec:
      containers:
        - name: pollution-sql-repository
          image: sersomon/pollution_sql_repository:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: MYSQL-POLLUTION
              valueFrom:
                configMapKeyRef:
                  name: persistence-url-configmap
                  key: mysql-pollution
            - name: MYSQL-USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL-PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
          - containerPort: 8080
