apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pollution-pvc-local
  namespace: urban
spec:
  # spec.storageClassName field from the PersistentVolume to match
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      type: mongo-pollution-pv-local
