apiVersion: v1
kind: Secret
metadata:
  name: municipal-api-secret
type: Opaque
data:
  admin-token: ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnpkV0lpT2lJeElpd2ljbTlzWlNJNklsSlBURVZmUVVSTlNVNGlMQ0pwYzNNaU9pSnpaWEp6YjIxdmJpSXNJbVY0Y0NJNk1UY3hOekE0Tmpjek9IMC5zV2xfeEJSbkl2aG96Wnh1V0V6UEQ4Qmtrb2tTRUNNOVJNTXNuNUNXT1U0
