apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-aggregate-pv-local
  namespace: urban
  labels:
    type: mongo-aggregate-pv-local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo/aggregate"
