apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-mobility-pv-local
  namespace: urban
  labels:
    type: mysql-mobility-pv-local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mysql/mobility"
