services:
  sql_db_pollution:
    image: mysql:8.0
    container_name: mysql_pollution
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=urbanAPIpassword
      - MYSQL_DATABASE=pollution
  nosql_db_pollution:
    image: mongo:4.4.6
    container_name: mongo_pollution
    ports:
      - 127.0.0.1:27017:27017
  sql_db_mobility:
    image: mysql:8.0
    container_name: mysql_mobility
    ports:
      - 127.0.0.1:3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=urbanAPIpassword
      - MYSQL_DATABASE=mobility
  nosql_db_mobility:
    image: mongo:4.4.6
    container_name: mongo_mobility
    ports:
      - 127.0.0.1:27018:27017
  nosql_db_aggregate:
    image: mongo:4.4.6
    container_name: mongo_aggregate
    ports:
      - 127.0.0.1:27019:27017
