apiVersion: v1
kind: Service
metadata:
  name: mongo-aggregate
  namespace: urban
spec:
  type: ClusterIP
  selector:
    app: mongo-aggregate
  ports:
    - port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-aggregate
  namespace: urban
spec:
  selector:
    matchLabels:
      app: mongo-aggregate
  template:
    metadata:
      labels:
        app: mongo-aggregate
        function: persistence
    spec:
      containers:
        - name: mongo-aggregate
          image: mongo:4.4.6
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-aggregate-pvc-local
      volumes:
        - name: mongo-aggregate-pvc-local
          persistentVolumeClaim:
            claimName: mongo-aggregate-pvc-local
