apiVersion: v1
kind: Service
metadata:
  name: mongo-pollution
  namespace: urban
spec:
  type: ClusterIP
  selector:
    app: mongo-pollution
  ports:
  - port: 27017
    targetPort: 27017

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-pollution
  namespace: urban
spec:
  selector:
    matchLabels:
      app: mongo-pollution
  template:
    metadata:
      labels:
        app: mongo-pollution
        function: persistence
    spec:
      containers:
      - name: mongo-pollution
        image: mongo:4.4.6
        ports:
        - containerPort: 27017